### ISSUE TITLE
[feature request] 自定义下载路径

### ISSUE THREAD

**Issue by taseikyo** [Peach-Coding/KindleHelper#15]
目前的下载路径是 KindleHelper-win-x64/downloads，希望可以自定义下载路径
另外也可以在“下载完成”页面加一个按钮“打开下载文件夹”或许体验更好

p.s. 这个应用好像没有图标有点丑啊😂
![20201112094853](https://user-images.githubusercontent.com/23132915/98884921-0d4cd700-24cc-11eb-840d-36ab208ac1aa.png)

**Comment by lt94** [comment]
> 目前的下载路径是 KindleHelper-win-x64/downloads，希望可以自定义下载路径
> 另外也可以在“下载完成”页面加一个按钮“打开下载文件夹”或许体验更好
> 
> p.s. 这个应用好像没有图标有点丑啊😂
> ![20201112094853](https://user-images.githubusercontent.com/23132915/98884921-0d4cd700-24cc-11eb-840d-36ab208ac1aa.png)

安排上~~

**Comment by lt94** [comment]
@taseikyo 打开下载文件的功能已经加上了~~图标的问题晚点再修改

**Comment by taseikyo** [comment]
> @taseikyo 打开下载文件的功能已经加上了~~图标的问题晚点再修改

很棒！

**Comment by lt94** [comment]
@taseikyo 哈哈～ps，其实还修复了苦瓜网盘的搜索问题
