### ISSUE TITLE
文件下载不了怎么删除

### ISSUE THREAD

**Issue by Wu0706** [Peach-Coding/KindleHelper#19]
文件下载不了，进度一直为0，请问怎么删除？不删除的话下载不了其他的。

**Comment by LeetaoGoooo** [comment]
@Wu0706 出现这种情况多半下载链接是来自城通网盘的。。。

**Comment by Wu0706** [comment]
谢谢回答，我发现放在那不管，过一会儿自己就下载好了

**Comment by LeetaoGoooo** [comment]
@Wu0706 哈哈，下载好了，你看一下文件是不是有问题，有的时候，现在城通网盘有的下载基本上都会失败
