### ISSUE TITLE
readme.md打包命令安装 pyinstaller写错了

### ISSUE THREAD

**Issue by mengrayan** [Peach-Coding/KindleHelper#2]
> pip install pyinstaller

RT

**Comment by lt94** [comment]
收到~~竟然拼写错误了~~谢谢指正

**Comment by lzhxwmr** [comment]
之前指出一行的下面一行也有typo
***
~~pyinstaller src\\**kindelHelper.spec**~~
pyinstaller src\\**kindleHelper.spec**
***
