### ISSUE TITLE
win

### ISSUE THREAD

**Issue by a310913262** [Peach-Coding/KindleHelper#22]
win版本怎么没有下载按钮呢

**Comment by LeetaoGoooo** [comment]
@a310913262 都有的吧～

**Comment by a310913262** [comment]
![image](https://user-images.githubusercontent.com/40455118/121653174-f8224000-cace-11eb-95bd-a726f4e14018.png)

**Comment by LeetaoGoooo** [comment]
@a310913262 在搜索框输入搜索的📚然后回车～

**Comment by a310913262** [comment]
![image](https://user-images.githubusercontent.com/40455118/121653765-9f9f7280-cacf-11eb-8091-6e15d556a067.png)

**Comment by a310913262** [comment]
可以了

**Comment by LeetaoGoooo** [comment]
@a310913262 OK
