### ISSUE TITLE
如果限制商用的话, 或许我们可以把 开源协议改为 GPL 3 或者其他商业不友好的开源协议

### ISSUE THREAD

**Issue by Kuri-su** [Peach-Coding/KindleHelper#3]
有注意到 现在的 开源协议是 MIT, 这个是极为宽松的开源协议, 无法限制软件被商业应用 ; )

来自 RMS 的凝视 2333

![](https://upload.wikimedia.org/wikipedia/commons/thumb/2/28/Richard_Stallman_at_LibrePlanet_2019.jpg/220px-Richard_Stallman_at_LibrePlanet_2019.jpg)

**Comment by lt94** [comment]
感谢提示~~已经修改为 GPL v3 协议了
