### ISSUE TITLE
English Translation

### ISSUE THREAD

**Issue by Seanmusse** [Peach-Coding/KindleHelper#5]
Hello! 
I was wondering if you would be interested in me translating this project, I would translate the README.md and make a new file called `EnglishKindleHelper.py` that is the same as `kindleHelper.py` but in English. If you're interested in this I will start working on it immediately :) 

### Translation from Google Translate
你好！
我想知道您是否对我翻译这个项目感兴趣，我将翻译README.md并创建一个名为`EnglishKindleHelper.py`'的新文件，该文件与`kindleHelper.py`相同，但使用英语。 如果您对此感兴趣，我将立即开始进行工作:)

**Comment by lt94** [comment]
> Hello!
> I was wondering if you would be interested in me translating this project, I would translate the README.md and make a new file called `EnglishKindleHelper.py` that is the same as `kindleHelper.py` but in English. If you're interested in this I will start working on it immediately :)
> 
> ### Translation from Google Translate
> 你好！
> 我想知道您是否对我翻译这个项目感兴趣，我将翻译README.md并创建一个名为`EnglishKindleHelper.py`'的新文件，该文件与`kindleHelper.py`相同，但使用英语。 如果您对此感兴趣，我将立即开始进行工作:)

It's glad that you can translate this project. This is project only can work in China. But ihis is a very good example for beginners to learn pyqt5 and python
