### ISSUE TITLE
命令行运行kindleHelper.py报异常

### ISSUE THREAD

**Issue by furrutton** [Peach-Coding/KindleHelper#7]
`搜索异常:[Errno 2] No such file or directory: ‘目录\\ziliaoH.db’`
这个异常有什么影响吗？而且点击搜索之后，经常搜不到任何东西。搜索音乐倒是挺靠谱，考虑做万能搜索？

**Comment by lt94** [comment]
> `搜索异常:[Errno 2] No such file or directory: ‘目录\\ziliaoH.db’`
> 这个异常有什么影响吗？而且点击搜索之后，经常搜不到任何东西。搜索音乐倒是挺靠谱，考虑做万能搜索？

这个是其中一个搜索源的保存的地方，是那个网盘选项的的结果数据库，没有的话，顶多网盘那个选项结果一直为空～～这么快就发现可以搜索其他的了，其实还可以搜电影之类的～～因为这个是从网盘检索出来的结果
