### ISSUE TITLE
script 'src\website\kankan.py' not found

### ISSUE THREAD

**Issue by lindsaymorgan** [Peach-Coding/KindleHelper#9]
windows 命令行 pyinstaller src\kindleHelper.spec 返回 script 'src\website\kankan.py' not found
似乎文件不见了？

**Comment by lindsaymorgan** [comment]
好像是从release下载的话有点问题 用gitclone之后好了

**Comment by lindsaymorgan** [comment]
以及build成功之后运行搜索一次成功 后面再打开搜索回车之后就会闪退了（不确定是什么问题

**Comment by lt94** [comment]
可能release的版本有问题～我今天重新发布一下～～是windows下build的吗？

**Comment by lindsaymorgan** [comment]
> 可能release的版本有问题～我今天重新发布一下～～是windows下build的吗？

是的~

**Comment by lt94** [comment]
> > 可能release的版本有问题～我今天重新发布一下～～是windows下build的吗？
> 
> 是的~

你试试重新build一下，我更新了一下代码~~这几天可能加新的搜索源

**Comment by lindsaymorgan** [comment]
> > > 可能release的版本有问题～我今天重新发布一下～～是windows下build的吗？
> > 
> > 
> > 是的~
> 
> 你试试重新build一下，我更新了一下代码~~这几天可能加新的搜索源

我重新git clone build了一下 似乎第二次搜索的时候程序还是会闪退（小声
以及正常情况下搜索完应该怎么下载呢？没找到下载按钮的样子

**Comment by lt94** [comment]
> > > > 可能release的版本有问题～我今天重新发布一下～～是windows下build的吗？
> > > 
> > > 
> > > 是的~
> > 
> > 
> > 你试试重新build一下，我更新了一下代码~~这几天可能加新的搜索源
> 
> 我重新git clone build了一下 似乎第二次搜索的时候程序还是会闪退（小声
> 以及正常情况下搜索完应该怎么下载呢？没找到下载按钮的样子

我已经发布了一个打包的版本，你试一下~~
